import type { Metadata } from "next";
import { Providers } from "../../components/providers";
import Navbar from "@/components/Navbar";
import { getCurrentSession } from "@/auth/session";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function MainAppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await getCurrentSession();

  return (
    <Providers>
      <Navbar user={user} />
      <main className="container mx-auto max-w-5xl mt-20 pb-10 px-2">
        {children}
      </main>
    </Providers>
  );
}
